package com.communication.lib_core.tools

/**
 * Created by LG
 * on 2022/3/10  17:10
 * Description：
 */


const val EVENTBUS_TOKEN_SUCCESS = "EVENTBUS_TOKEN_SUCCESS"
const val EVENTBUS_LOGIN_SUCCESS = "EVENTBUS_LOGIN_SUCCESS"
const val EVENTBUS_LOGOUT_SUCCESS = "EVENTBUS_LOGOUT_SUCCESS"
const val EVENTBUS_TOAST_STRING = "EVENTBUS_TOAST_STRING"

const val EVENTBUS_HOME_APPS_SUCCESS = "EVENTBUS_HOME_APPS_SUCCESS"
const val EVENTBUS_APP_CLICK = "EVENTBUS_APP_CLICK"
const val EVENTBUS_MESSAGE_ITEM_CLICK = "EVENTBUS_MESSAGE_ITEM_CLICK"